# Metrics (CLIP-Score)

### Preliminaries

In [27]:
import os
import json
import pandas as pd
import numpy as np

### Calculate mean CLIP-Score (for each video / each subject)

In [28]:
# Get scores for all metrics averagin for a PARTICULAR BENCHMARK
def get_mean_metrics(metrics_path):

    with open(metrics_path, 'r') as f:
        metrics = json.load(f)

    names = list(metrics.keys())
    
    dfs = {}
    dfs['videos'] = pd.DataFrame(columns=names)
    dfs['subs'] = pd.DataFrame(columns=names)
    
    for name in metrics:
        
        video_names = list(metrics[name].keys())
        dfs[name] = pd.DataFrame(columns=video_names)
        
        for key in video_names:
            for sub in metrics[name][key].keys():
                try:
                    scores = metrics[name][key][sub]
                except:
                    continue
                scores = [s for s in scores if s is not None]
                dfs[name].loc[sub, key] = np.mean(scores) if scores else None
    
        for key in video_names:
            dfs['videos'].loc[key, name] = dfs[name][key].mean()
            
        for sub in dfs[name].index:
            dfs['subs'].loc[sub, name] = dfs[name].mean(axis=1)[sub]
        
    return dfs

### Get results

In [31]:
metrics_path = "/home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/metrics/metrics.json"
dfs = get_mean_metrics(metrics_path)

In [32]:
dfs["videos"]

,fmri-monkeys-29000,flow-matching-prior-fmri-monkeys-29000-13000,fmri-monkeys-44000,flow-matching-prior-fmri-monkeys-44000-10000
monkey1,0.253734,0.629466,0.309835,0.66796
monkey2,0.270462,0.639267,0.312165,0.646697
monkey5,0.241954,0.623674,0.283865,0.643836

In [33]:
dfs["subs"]

,fmri-monkeys-29000,flow-matching-prior-fmri-monkeys-29000-13000,fmri-monkeys-44000,flow-matching-prior-fmri-monkeys-44000-10000
sub-01,0.261761,0.640452,0.3073,0.670009
sub-02,0.244408,0.622822,0.299492,0.6571
sub-03,0.260486,0.636321,0.312684,0.673718
sub-04,0.252803,0.626066,0.298639,0.648511
sub-05,0.253419,0.626145,0.295428,0.648219
sub-06,0.252231,0.627082,0.30104,0.649787
sub-07,0.255007,0.630169,0.304264,0.653228
sub-08,0.255388,0.631744,0.305531,0.653704
sub-09,0.288191,0.67798,0.33178,0.699832
sub-10,0.254731,0.633128,0.300743,0.654362
sub-11,0.253543,0.624761,0.298345,0.64979
sub-12,0.252801,0.629559,0.298096,0.652777
sub-13,0.252816,0.628953,0.304047,0.651986
sub-14,0.256708,0.632705,0.299034,0.654107
sub-15,0.269609,0.64313,0.316367,0.665718
sub-16,0.253033,0.62614,0.301878,0.648332
sub-17,0.263347,0.633711,0.308202,0.65712
sub-18,0.252234,0.625376,0.309237,0.671179
sub-19,0.249841,0.630089,0.30362,0.651505
sub-20,0.246085,0.627705,0.296819,0.65025
sub-21,0.252647,0.628471,0.301749,0.650034
sub-22,0.2547,0.625541,0.29566,0.648019

In [34]:
dfs["flow-matching-prior-fmri-monkeys-29000-13000"]

         monkey1   monkey2   monkey5
sub-01  0.640452       NaN       NaN
sub-02  0.622822       NaN       NaN
sub-03  0.636321       NaN       NaN
sub-04  0.622753  0.640939  0.614508
sub-05  0.622406  0.636968  0.619059
sub-06  0.624114  0.631891  0.625241
sub-07  0.623117  0.639563  0.627827
sub-08  0.629683  0.636865  0.628685
sub-09   0.67798       NaN       NaN
sub-10  0.626589  0.640058  0.632736
sub-11  0.620193  0.629282  0.624808
sub-12  0.630995  0.642036  0.615645
sub-13  0.632901  0.633906  0.620053
sub-14  0.624724   0.64407  0.629322
sub-15  0.619579  0.673512  0.636299
sub-16    0.6258  0.632832  0.619789
sub-17  0.630548  0.645595  0.624988
sub-18  0.625376       NaN       NaN
sub-19  0.624882  0.641883  0.623503
sub-20  0.625406   0.63968  0.618029
sub-21  0.635108  0.631015  0.619291
sub-22   0.62651  0.627449  0.622665