# Metrics (CLIP-Score)

### Preliminaries

In [1]:
import os
import json
import pandas as pd
import numpy as np

### Calculate mean CLIP-Score (for each video / each subject)

In [5]:
# Get scores for all metrics averagin for a PARTICULAR BENCHMARK
def get_mean_metrics(
    metrics_path: str = '/home/jovyan/shares/SR004.nfs2/nkiselev/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/metrics/metrics.json'
):

    with open(metrics_path, 'r') as f:
        metrics = json.load(f)

    names = list(metrics.keys())
    
    dfs = {}
    dfs['videos'] = pd.DataFrame(columns=names)
    dfs['subs'] = pd.DataFrame(columns=names)
    
    for name in metrics:
        
        video_names = list(metrics[name].keys())
        dfs[name] = pd.DataFrame(columns=video_names)
        
        for key in video_names:
            for sub in metrics[name][key].keys():
                try:
                    scores = metrics[name][key][sub]
                except:
                    continue
                scores = [s for s in scores if s is not None]
                dfs[name].loc[sub, key] = np.mean(scores) if scores else None
    
        for key in video_names:
            dfs['videos'].loc[key, name] = dfs[name][key].mean()
            
        for sub in dfs[name].index:
            dfs['subs'].loc[sub, name] = dfs[name].mean(axis=1)[sub]
        
    return dfs

### Get results

In [6]:
metrics_path = '/home/jovyan/shares/SR004.nfs2/nkiselev/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/metrics/metrics.json'
dfs = get_mean_metrics()

In [7]:
dfs['videos']

         improved-dataloader eeg-zeros-monkeys
dme                 0.099449               NaN
dmh                 0.097164               NaN
tp                  0.096893               NaN
inscapes            0.088971               NaN
monkey1             0.070744          0.037642
monkey2              0.11253          0.057867
monkey5             0.103985          0.054155

In [8]:
dfs['subs']

       improved-dataloader eeg-zeros-monkeys
sub-01            0.117181          0.049255
sub-02            0.116841          0.048401
sub-03            0.124905          0.047692
sub-04            0.085871          0.048024
sub-05            0.088922          0.048497
sub-06            0.086471          0.047886
sub-07            0.088428          0.048275
sub-08            0.088939          0.048297
sub-09            0.138753          0.089423
sub-10            0.098537          0.048075
sub-11             0.08818          0.048711
sub-12            0.089809          0.048287
sub-13             0.08956          0.048284
sub-14            0.091733          0.047063
sub-15            0.091582          0.049389
sub-16             0.08648          0.048531
sub-17            0.095094          0.046315
sub-18            0.120481          0.048432
sub-19            0.090556          0.047805
sub-20            0.092385          0.048246
sub-21              0.0893           0.04726
sub-22            0.092863          0.047486

In [9]:
dfs['improved-dataloader']

             dme       dmh        tp  inscapes   monkey1   monkey2   monkey5
sub-01  0.122711       NaN  0.127444  0.133588  0.084981       NaN       NaN
sub-02  0.117781       NaN   0.12977  0.129474  0.090337       NaN       NaN
sub-03  0.124935       NaN  0.135567  0.137097   0.10202       NaN       NaN
sub-04  0.093985  0.091762   0.07561     0.077  0.061901  0.103507  0.097331
sub-05  0.092675  0.092113  0.081334  0.088911  0.064778  0.104933  0.097709
sub-06  0.088808  0.091671  0.087151  0.078928  0.058979  0.103927  0.095832
sub-07  0.090644  0.097211  0.090465  0.083142  0.056631  0.102627  0.098272
sub-08  0.091469  0.098499  0.079869  0.070743  0.058106  0.114528  0.109355
sub-09  0.136836       NaN   0.14878       NaN  0.130643       NaN       NaN
sub-10  0.093361  0.105993   0.09227  0.079551   0.05624  0.137484  0.124861
sub-11  0.091904  0.099297  0.090211  0.075744  0.058699   0.11135  0.090057
sub-12  0.092784  0.092676  0.093219    0.0729  0.059854  0.111096  0.106134
sub-13  0.080417  0.092353  0.084015  0.081729  0.071561  0.109826  0.107019
sub-14   0.08706  0.096083  0.084464  0.084539  0.069343  0.113777  0.106867
sub-15  0.089453  0.100603  0.084876  0.072514  0.057692  0.128362  0.107573
sub-16  0.084921  0.097021  0.080137  0.076054  0.051022  0.120234  0.095972
sub-17  0.103178  0.104598  0.090166  0.076309  0.073388  0.111996  0.106026
sub-18  0.121956       NaN  0.130138   0.14074   0.08909       NaN       NaN
sub-19   0.09811     0.093    0.0751   0.08359  0.066143  0.109205  0.108741
sub-20  0.095487  0.102677  0.100349  0.072341  0.066218  0.104481  0.105138
sub-21  0.091576  0.094805  0.087057  0.073106  0.060125  0.114258  0.104172
sub-22  0.097826  0.101433  0.083664  0.080387  0.068619  0.111423  0.106685